name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-source:
    uses: jholtan/actions/.github/workflows/build.yaml@main
