name: Build and Deploy

on:
  push:
    branches: ["nada"]

jobs:
  build-and-deploy:
    uses: jholtan/demoapp/.github/workflows/deploy.yaml@master
    permissions:
      id-token: write
      packages: write
      attestations: write
